version: '3'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - JWT_SECRET=secret
      - MONGO_DSN=mongodb://root:password@mongo:27017/
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
